<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<!-- Define Target Framework constants -->
		<TfmNet>net9.0</TfmNet>
		<TfmNetWindows>net9.0-windows</TfmNetWindows>
		<TfmNetFx>net472</TfmNetFx>

		<TargetFramework>$(TfmNet)</TargetFramework>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<RepositoryUrl>https://github.com/dotnet/winforms-designer</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_GetFilesToPackage</TargetsForTfmSpecificContentInPackage>
		<RunPostBuildEvent>Always</RunPostBuildEvent>
		<PackageVersion>$([System.DateTime]::Now.ToString("1.yM.dHmm"))</PackageVersion>
		<AssemblyVersion>$([System.DateTime]::Now.ToString("yyyy.MM.dd.HHmm"))</AssemblyVersion>
	</PropertyGroup>

	<Target Name="_GetFilesToPackage">
		<ItemGroup>
			<_File Include="$(SolutionDir)\TileRepeater.Controls\bin\$(Configuration)\$(TfmNetWindows)\TileRepeater.Controls.dll" />

			<!--We need this during Control development, so we get proper Debug-Support at runtime. -->
			<_File Include="$(SolutionDir)\TileRepeater.Controls\bin\$(Configuration)\$(TfmNetWindows)\TileRepeater.Controls.pdb" />

			<_File Include="$(SolutionDir)\TileRepeater.Designer.Client\bin\$(Configuration)\$(TfmNetFx)\TileRepeater.Designer.Client.dll" TargetDir="Design/WinForms" />
			<_File Include="$(SolutionDir)\TileRepeater.ClientServerProtocol\bin\$(Configuration)\$(TfmNetFx)\TileRepeater.ClientServerProtocol.dll" TargetDir="Design/WinForms" />
			<_File Include="$(SolutionDir)\TileRepeater.Designer.Server\bin\$(Configuration)\$(TfmNetWindows)\TileRepeater.Designer.Server.dll" TargetDir="Design/WinForms/Server" />
			<_File Include="$(SolutionDir)\TileRepeater.ClientServerProtocol\bin\$(Configuration)\$(TfmNetWindows)\TileRepeater.ClientServerProtocol.dll" TargetDir="Design/WinForms/Server" />
		</ItemGroup>

		<ItemGroup>
			<TfmSpecificPackageFile Include="@(_File)" PackagePath="$(BuildOutputTargetFolder)/$(TargetFramework)/%(_File.TargetDir)" />
		</ItemGroup>
	</Target>

	<Target Name="CopyPackage" AfterTargets="Pack">
		<Copy SourceFiles="$(OutputPath)..\$(PackageId).$(PackageVersion).nupkg" 
			  DestinationFolder="$(SolutionDir)\NuGet\BuildOut\"/>
	</Target>
	
</Project>
